name: push, and deploy to OpenShift

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-deploy:
    name: Build image and deploy to OpenShift
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "latest"

      - name: Log in to OpenShift Cluster
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.rm3.7wse.p1.openshiftapps.com:6443
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: false

      - name: Log in to OpenShift Image Registry
        run: |
          podman login \
            -u $(oc whoami) \
            -p $(oc whoami -t) \
            default-route-openshift-image-registry.apps.rm3.7wse.p1.openshiftapps.com

      - name: Build and Tag Podman Image
        run: |
          podman build \
            --tag default-route-openshift-image-registry.apps.rm3.7wse.p1.openshiftapps.com/mmdev26-dev/hello-webapp:latest \
            --file Containerfile \
            .

      - name: Push to OpenShift
        run: |
          oc project mmdev26-dev
          podman push default-route-openshift-image-registry.apps.rm3.7wse.p1.openshiftapps.com/mmdev26-dev/hello-webapp:latest